<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">  <!--Burası POM'un ana elemanı-->
  <modelVersion>4.0.0</modelVersion>  <!--Maven POM model formatı-->
  <groupId>com.simay</groupId> <!--Projeyi/organizasyonu tanımlayan kimlik-->
  <artifactId>maven-practice</artifactId> <!--Üretilen Maven artifact'inin/projenin adı-->
  <packaging>jar</packaging> <!--Maven'in build sonucunda ne tür bir artifact oluşturacağını söyler-->
  <version>1.0-SNAPSHOT</version> <!--Projenin versiyonu 1.0-SNAPSHOT → geliştirilmekte olan versiyon-->
  <name>maven-practice</name> <!--/Projenin görünen adı. Bu artifactId ile aynı olmak zorunda değil.-->
  <url>http://maven.apache.org</url>
  <dependencies> <!--Yani Maven'e: "Bu proje JUnit'e ihtiyaç duyuyor." diyoruz.-->
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>3.8.1</version>
      <scope>test</scope> <!--JUnit dependency'sinin test amacıyla kullanılacağını söylüyor-->
    </dependency>
  </dependencies>
</project>
